### ISSUE TITLE
Layout without caching to allow fast measurement

### ISSUE THREAD

**Issue by joshtynjala** [MaxDidIt/firetype#9]
From the forums:

> The most time consuming task during layouting would be caching characters that are encountered for the first time. Maybe I can implement a functionality that only positions the characters and ignores the cache, so that you can get the measurements without much impact on the performance.

**Comment by MaxDidIt** [comment]
I have changed the API so that the update() method of HardwareText now accepts the optional cacheGlyphs parameter.

If this parameter is false, then the text will only be layouted, no polygon shapes for glyphs will be constructed or cached. The changes will be available in the next version of firetype released. I guess the next version should be ready next week.

**Comment by joshtynjala** [comment]
Thank you!
